#!/usr/bin/env python3
"""Check Git ignore guards for generated book projects and private-use output."""

from __future__ import annotations

import sys
from pathlib import Path


PUBLIC_PROJECT_GITIGNORE = """# Generated by books/scripts/create_book_project.py.
# Book-project working files are local production state.
# GitHub may track only versioned public release artifacts under output/release/.
*
!.gitignore
!output/
output/*
!output/release/
!output/release/**
output/release/*_private_*.epub
"""

PRIVATE_SENTINEL_GITIGNORE = """# Private-use book projects stay local.
# Do not publish source text, translations, QA records, EPUB output, or private artifacts.
*
!.gitignore
"""

REQUIRED_BOOKS_GITIGNORE_SNIPPETS = [
    "private/**",
    "!private/.gitignore",
    "*/*/*",
    "!*/*/.gitignore",
    "!*/*/output/release/",
    "!*/*/output/release/**",
]
FORBIDDEN_PUBLIC_RELEASE_PATTERNS = [
    "*_private_*.epub",
]

REFERENCE_PROJECTS = {
    "zh-Hans/7_刺青_谷崎润一郎",
}


def repo_paths() -> tuple[Path, Path]:
    books_root = Path(__file__).resolve().parents[1]
    return books_root.parent, books_root


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def public_book_dirs(books_root: Path) -> list[Path]:
    result: list[Path] = []
    for target_dir in books_root.iterdir():
        if not target_dir.is_dir() or target_dir.name in {"private", "scripts", "node_modules", "tools"}:
            continue
        for book_dir in target_dir.iterdir():
            if book_dir.is_dir() and book_dir.name[:1].isdigit():
                result.append(book_dir)
    return sorted(result)


def fail(issues: list[str], message: str) -> None:
    issues.append(message)


def main() -> None:
    _repo_root, books_root = repo_paths()
    issues: list[str] = []

    books_gitignore = read_text(books_root / ".gitignore")
    for snippet in REQUIRED_BOOKS_GITIGNORE_SNIPPETS:
        if snippet not in books_gitignore:
            fail(issues, f"books/.gitignore missing required rule: {snippet}")

    private_gitignore = books_root / "private" / ".gitignore"
    if read_text(private_gitignore) != PRIVATE_SENTINEL_GITIGNORE:
        fail(issues, "books/private/.gitignore must block all private-use contents except itself.")

    for book_dir in public_book_dirs(books_root):
        relative = book_dir.relative_to(books_root).as_posix()
        if relative in REFERENCE_PROJECTS:
            continue
        expected = PUBLIC_PROJECT_GITIGNORE
        actual = read_text(book_dir / ".gitignore")
        if actual != expected:
            fail(issues, f"{relative}/.gitignore must allow only output/release/ artifacts.")
        release_dir = book_dir / "output" / "release"
        if release_dir.is_dir():
            for pattern in FORBIDDEN_PUBLIC_RELEASE_PATTERNS:
                for path in release_dir.glob(pattern):
                    fail(
                        issues,
                        f"{relative}/output/release contains private-use artifact: {path.name}",
                    )

    if issues:
        print("gitignore policy FAIL")
        for issue in issues:
            print(f"- {issue}")
        sys.exit(1)

    print("gitignore policy PASS")


if __name__ == "__main__":
    main()
